spring:
  application:
    name: zuul
  profiles:
      active: local
  rabbitmq:
    addresses: 192.168.14.97
    port: 5672
    username: guest
    password: guest

server:
  port: 10002

zuul:
  retryable: true   #转发重试关闭
  routes:
    config-client-service:
      path: /config-client-service/**
      serviceId: config-client-service

#服务调用超时配置
hystrix:
  command:
    config-client-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000   #hystix的连接超时时间

ribbon:
  ConnectTimeout: 3500 #创建连接的超时时间
  ReadTimeout: 4000 #路由转发请求的超时时间
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0 #本机不再重试
  MaxAutoRetriesNextServer: 5

---
###################  开发环境的profile  ###################
spring:
  profiles: local
  zipkin:
      #base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    #hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/

      #http://www.itkeyword.com/doc/5016272925572737815/zuul-ribbon-hystrix-not-retrying-on-different-instance
      #http://www.jb51.net/article/128511.htm
      #https://www.jianshu.com/p/cb69bb385d24

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG