spring:
  application:
    name: @register-name-eureka@
  profiles:
      active: local
      
#访问服务注册中心管理页面需要加密码
security:  
  basic:  
    enabled: true  
  user:  
    name: @register-visite-name@
    password: @register-visite-passwd@
      