server:
  port: 10101
  
develop:
  open: true #是否开启开发者模式,开启则开启DevelopFilter,走接口不用传jwt token
  user-id: 1 #开发环境下,传给下游服务的当前用户id,默认为1
  
spring:
  redis:
    host: 192.168.14.97
    port: 6379
    password:
  rabbitmq:
    addresses: 192.168.14.97
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${register-visite-name}:${register-visite-passwd}@localhost:10001/eureka/
    registry-fetch-interval-seconds: 3  #获取服务的刷新时间

logging:
  level:
    root: INFO
    com.iciyun: INFO
  file: /var/data/log/cibei-gate.log
