spring:
  application:
    name: @service-name-gate@
  profiles:
    active: local

#访问服务注册中心管理页面需要加密码
register-visite-name: @register-visite-name@
register-visite-passwd: @register-visite-passwd@

#各微服务相关数据配置
cservice:
  nodeMap:
    service-name-order: @service-name-order@

zuul:
  retryable: false   #转发重试关闭
  add-host-header: true

  routes:
    auth-service: /@service-name-auth@/**
    data-service: /@service-name-data@/**
    order-service:
      path: /@service-name-order@/**
      serviceId: order-service
      retryable: true
    inv-service: /@service-name-inv@/**
    report-service: /@service-name-report@/**
    api-gate:
      path: /gate/**
      url: forward:/gate




#第三方账号设置
t3party:
  wx: #微信
    mp: #微信小程序
      appid: wxc7146eaca4603fd1
      appSecret: 8fd3937e38a7ce419a029754e0a5179d
    web: #微信网站
      appid: wx2d364aad2b74137b
      appSecret: c8ed639139b27f6d84627360643ec3a5

#WebSocket
ws:
  enabled: false
  
jwt:
  header: X-Auth-Token        #http请求头所需要的字段
  param: tk                   #http请求参数所需要的字段
  secret: CibeiSecret         #jwt秘钥
  expiration: 2592000         #30天 单位:秒，适用小程序端TOKEN过期时间
  shortExpiration: 1800000       #30分钟 单位:秒，适用PC端TOKEN过期时间
  auth-path: /gate/monitor/open/**,/gate/login/**,/gate/wx/auth/**,/gate/mp/auth/**,/gate/captcha/**,/**-service**/swagger-ui.html,/**-service**/webjars/springfox-swagger-ui/**,/**-service**/swagger-resources/**,/**-service**/v2/api-docs**,/**-service**/druid/**
  
#服务间调用超时配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000   #hystix的连接超时时间 5秒
    order-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000   #hystix的连接超时时间 5秒

ribbon:
  ConnectTimeout: 3500 #创建连接的超时时间 2秒
  ReadTimeout: 4000 #路由转发请求的超时时间 5秒
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0 #本机不再重试
  MaxAutoRetriesNextServer: 5